### PR TITLE
Login out

### PR DESCRIPTION
**Pull request by danfstucky**
login and logout functionality added.
@sl7v3 @jwiebe17

### CODE REVIEW

**Comment by sl7v3** [comment]
+1 - Sign up works, I can login and logout as well.

**Comment by sl7v3** [comment]
This looks good Dan. Are you going to merge it or are you waiting on Joel?

**Comment by danfstucky** [comment]
I was just waiting for you to merge your other branch.   Will merge this today

**Comment by danfstucky** [comment]
Merged here: https://github.com/danfstucky/LeagueSpec/commit/167fef10b45817cdaf9b729779f08bf51d11a939

**Pull request closed without merging**
