### PR TITLE
BootstrapInclusionBranch

### PR DESCRIPTION
**Pull request by sl7v3**
@danfstucky 
@jwiebe17 
This new branch is the same as the one I recently edited, except I added bootstrap features to some asset files so we can all use that capability as we go forward.

### CODE REVIEW

**Comment by danfstucky** [comment]
This branch should only contain the additional stuff regarding bootstrap, not all the other commits.

**Comment by danfstucky** [comment]
I am not too familiar with bootstrap, but I don't think you have actually integrated it at all with these changes.  There is a lot more to it than this.  Firstly, bootstrap requires a css framework and natively runs using the `Less CSS` language.  Rails comes with sass already built in though, so we can use that instead.  I think I will handle incorporating the bootstrap capabilities.

**Comment by sl7v3** [comment]
I would say you try to use some bootstrap features and see if this branch works or not. I came about the Less method of incorporating bootstrap but I found the one I used the easiest. If you are going to try a different way to incorporate bootstrap, let me know when you do it because I plan on using bootstrap grids/tabs for the profile mock-up page.

**Comment by jwiebe17** [comment]
Where do we stand on this?

**Comment by danfstucky** [comment]
This pull request should be closed and the changes regarding bootstrap listed here should be abandoned.  Do not merge this request.

**Pull request closed without merging**
