### PR TITLE
Signup page

### PR DESCRIPTION
**Pull request by danfstucky**
@sl7v3 @jwiebe17 
This is a large pull request.  I knew there was going to be some merge conflicts so I merged Sulaimon's most recent changes into this branch and modified the conflicts so that is why his code appears as changes here.  This pull request adds the signup feature, backed by a database, and input validation. Layout used here is just a starter and will be changed in the future.

The `bcrypt` gem is added here for encrypting user passwords so user data is secure even if an attacker gains access to our database.  You will have to run a `bundle install` after pulling this branch when testing.  Unfortunately, bcrypt has problems running on ruby 2.2.3 and windows.  I think I fixed it, but there is a very good chance it will not run on your machines.  If that happens, contact me offline and I will give some help.  

Lastly, a note on testing databases:
Ruby on rails uses separate databases for the development and production environments of the app.  Since our app has not been deployed yet, a production environment does not exist.  A great way for testing that new users are added to the db is to use a tool called SqliteBrowser.  You can load our development db into it and view all the user records currently in the db.

### CODE REVIEW

**Comment by sl7v3** [comment]
@danfstucky I had a bcrypt related error after trying to run rails server. I will bring my laptop to class tomorrow for you to take a look at it.

**Comment by jwiebe17** [comment]
I've pulled and tried to run on localhost but wasn't getting anything.

**Comment by sl7v3** [comment]
@jwiebe17 what does not getting anything mean? Is there  specific error? Did your server start after running rails s?

**Comment by danfstucky** [comment]
@jwiebe17 You should have gotten a bcrypt error.  We can discuss in person soon.

**Comment by jwiebe17** [comment]
Yes I got a bcrypt error.I have version 3.1.10, error says 'require': cannot load such file -- bcrypt_ext(LoadError)

**Comment by sl7v3** [comment]
@jwiebe17 If you get on Slack, there is a document you could follow to resolve the issue or you could bring your laptop to class on Friday.

**Comment by sl7v3** [comment]
+1

**Comment by danfstucky** [comment]
Merged here: https://github.com/danfstucky/LeagueSpec/commit/2d083dbb746b5e1721f5c013dfc2ac67ae2d0916

**Pull request closed without merging**
